# Generated by Django 5.0a1 on 2023-10-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_group_members_group_tags_group_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
