# Generated by Django 5.0a1 on 2023-10-20 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_channel_private_channel_slug_group_private_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='invite_links',
            field=models.ManyToManyField(blank=True, to='chat.invitelink'),
        ),
        migrations.AddField(
            model_name='group',
            name='invite_links',
            field=models.ManyToManyField(blank=True, to='chat.invitelink'),
        ),
    ]
